[LoongArch] support relaxation of pcalau12i/addi.d->pcaddi.d and alignment
rui314/mold pull request #1317
Opened 2024-07-26 09:15 UTC by ywgrit

Support relaxation on LoongArch.

Now just a few case of relaxation has been added to see if these works finely: 1) pcalau12i/addi.d->pcaddi.d, 2)alignment. If we do not apply any other relaxation except alignment, then alignment relaxation may not be applied nither.

2024-07-26 10:01 UTC, rui314 requested changes
This PR needs multiple rounds of code review. I'm not going into the details during the first round because it needs reworking. In short, you should take some time to read arch-riscv.cc more carefully and take the same approach in this file. This PR is not aligned well with other parts of our linker.

2024-07-26 10:09 UTC, ywgrit commented on elf/arch-loongarch.cc
> +loongarch_relax_pcala_addi(Context<E> &ctx, InputSection<E> &isec,
Thanks for advice, I will read riscv part carefully before take more change.

2024-07-27 02:15 UTC, rui314 commented
It's much easier to actually do than to point out every detail about how to do it, so I've made a few changes to demonstrate how to relax relocations. Now you can add new relaxations based on my changes. Please read arch-riscv64.cc carefully and do the same thing. I believe LoongArch's relaxation is modeled after the RISC-V's model, and I don't think you need to invent something new to handle it.

2024-07-29 08:05 UTC, rui314 commented
Let me close this PR because it's going to be a major rewrite, and I'm also getting a notification every time you force-push a new commit to your branch. Please create a new PR once you are ready for another round of review.

2024-07-29 08:05 UTC, closed without merging

2024-07-29 08:31 UTC, ywgrit commented
> Let me close this PR because it's going to be a major rewrite, and I'm also getting a notification every time you force-push a new commit to your branch. Please create a new PR once you are ready for another round of review.

Sorry for I forgot notifications would be sent to you once I push a commit. New pr will be created after carefully modifications.

2024-07-29 08:56 UTC, ywgrit commented
> It's much easier to actually do than to point out every detail about how to do it, so I've made a few changes to demonstrate how to relax relocations. Now you can add new relaxations based on my changes. Please read arch-riscv64.cc carefully and do the same thing. I believe LoongArch's relaxation is modeled after the RISC-V's model, and I don't think you need to invent something new to handle it. Do no try to port the existing code you guys have wrote for other linkers to mold; it would never work. Instead, write completely new code for mold. It shouldn't be too hard -- it should actually be much easier than for the other linkers.

Thanks, Rui. 
And you are right, Some of the previous work was ported from gnu ld to mold, and after reading about the implementation of riscv, I will try to get loongarch's implementation of this part aligned with riscv as much as possible. Really appreciate for writing the template code on loongarch.